version: 2.1
commands:
  install-bazel:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/linux.sh
      - run: bash ./linux.sh && rm ./linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/rbe.sh
      - run: bash ./rbe.sh && rm ./rbe.sh          

  run-bazel:
    parameters:
      command:
        type: string
    steps:
      - run:
          command: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>
          no_output_timeout: 120m

  run-grakn:
    steps:
      - run-bazel:
          command: bazel run //test:grakn-extractor -- dist/grakn-core-all-linux
      - run: nohup ./dist/grakn-core-all-linux/grakn server start

  run-neo4j:
    steps:
      - run: sudo add-apt-repository -y ppa:openjdk-r/ppa
      - run: curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
      - run: curl https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
      - run: sudo apt-get update
      - run: wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
      - run: echo 'deb https://debian.neo4j.com stable 4.1' | sudo tee -a /etc/apt/sources.list.d/neo4j.list
      - run: sudo apt-get update
      - run: sudo apt-get install neo4j=1:4.1.0
      - run: sudo update-java-alternatives --jre --set java-1.11.0-openjdk-amd64
      - run: sudo neo4j start

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/simulation
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel build //...
      - run:
          name: Verify dependencies/maven/artifacts.snapshot
          command: |
            dependencies/maven/update.sh
            git diff --exit-code dependencies/maven/artifacts.snapshot
      - run: bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list

  test-end-to-end-neo4j:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/simulation
    steps:
      - install-bazel
      - checkout
      - run-neo4j
      - run: bazel run //:simulation -- -d neo4j -n

  test-comparison-grakn-and-neo4j:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/simulation
    steps:
      - install-bazel
      - checkout
      - run-grakn
      - run-neo4j
      - run: bazel test //test:simulation-test --test_output=all --test_timeout=7200

workflows:
  version: 2
  simulation:
    jobs:
      - build
      - test-end-to-end-neo4j:
          requires:
            - build
      - test-end-to-end-grakn:
          requires:
            - build
      - test-comparison-grakn-and-neo4j:
          requires:
            - build
