#
# Copyright (C) 2021 Vaticle
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

agents:
  # For each agent select a `mode`, `RUN` to run without tracing, `TRACE` to run with tracing, and `OFF` to not run at all
  - name: "PersonAgent"
    mode: RUN
  - name: "FriendshipAgent"
    mode: RUN
  - name: "MarriageAgent"
    mode: RUN
  - name: "ParentshipAgent"
    mode: RUN
  - name: "MaritalStatusAgent"
    mode: TRACE
  - name: "LineageAgent"
    mode: TRACE
  - name: "NationalityAgent"
    mode: TRACE
  - name: "CitizenshipAgent"
    mode: TRACE

traceSampling:
  # Options: `"every"` for every K traces; `"log"` for logarithm with base N
  function: "every"
  arg: 1

runParams:
  randomSeed: 1
  iterations: 5
  scaleFactor: 2
  databaseName: "simulation-reasoning"

modelParams:
  ageOfFriendship: 1
  ageOfAdulthood: 2
  yearsBeforeParentship: 1