# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]
    typedb-behaviour: [build]
    typedb-protocol: [build, release]

build:
  correctness:
    benchmark-tpcc-typedb2:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        tool/typedb2/setup.sh
        tool/execute-tpcc.sh --scalefactor=100 --warehouses=4 typedb2
        tool/typedb2/teardown.sh
    benchmark-tpcc-typedb3:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        tool/typedb3/setup.sh
        tool/execute-tpcc.sh --scalefactor=100 --warehouses=4 typedb3
        tool/typedb3/teardown.sh
    benchmark-tpcc-mongodb:
      image: typedb-ubuntu-22.04
      machine: 16-core-64-gb
      command: |
        tool/mongodb/setup.sh
        tool/execute-tpcc.sh --scalefactor=100 --warehouses=4 mongodb
        tool/mongodb/stop-server.sh